[package]
name = "fix-path-env"
version = "0.1.0"
authors = [ "Tauri Programme within The Commons Conservancy" ]
license = "Apache-2.0 OR MIT"
edition = "2021"

[dependencies]
thiserror = "1"

[target."cfg(not(target_os = \"windows\"))".dependencies]
strip-ansi-escapes = "0.2"
