name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  clippy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v5
      - name: install webkit2gtk
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev
      - name: Install clippy with stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy --manifest-path=Cargo.toml --all-targets --all-features -- -D warnings
